/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health-check style greeting
         * @description Public. Useful to verify a deployment.
         */
        get: operations["hello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's tasks
         * @description Returns one page of the authenticated user's tasks, oldest first. Keep requesting pages,
         *     passing back the previous `nextToken`, until `nextToken` is `null`. A page can be empty
         *     while a token is still returned. Tokens are opaque and only work for the user they were
         *     issued to.
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Create a task
         * @description The server generates `id` (a time-sortable UUID, version 7) and `createdAt`, sets `ownerId` to the authenticated
         *     user and sets `done` to `false`. The request must use `Content-Type: application/json`.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id (a UUID). */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** Get one task */
        get: operations["getTask"];
        /**
         * Partially update a task (deprecated, use PATCH)
         * @deprecated
         * @description **Deprecated: use `PATCH /tasks/{id}`**, which accepts the same body and answers with the
         *     updated task instead of a message. This operation keeps working unchanged until the sunset
         *     date, 2027-04-03, and may be removed after it. Every response of this operation carries the
         *     `Deprecation`, `Sunset` and `Link` headers (responses produced by API Gateway itself, such as
         *     `401`, do not).
         *
         *     Partial update despite the `PUT` verb: only the fields sent are changed, and at least one
         *     of `done`, `title` or `description` is required. Other fields (such as `id`, `ownerId`
         *     or `createdAt`) are ignored. The request must use `Content-Type: application/json`.
         */
        put: operations["updateTask"];
        post?: never;
        /** Delete a task */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * Partially update a task
         * @description Only the fields sent are changed, and at least one of `done`, `title` or `description` is
         *     required. Other fields (such as `id`, `ownerId` or `createdAt`) are ignored. Answers with the
         *     task as it is after the change. The request must use `Content-Type: application/json`.
         *
         *     This is the replacement for the deprecated `PUT /tasks/{id}`, which accepts the same body.
         */
        patch: operations["patchTask"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: {
            message: string;
        };
        ValidationError: {
            message: string;
            /** @description One entry per failing field, as `<json pointer> <reason>`. */
            errors: string[];
        };
        CreateTask: {
            /** @description Non-empty string. */
            title: string;
            /** @default  */
            description: string;
        };
        UpdateTask: {
            title?: string;
            description?: string;
            done?: boolean;
        };
        /**
         * @example {
         *       "id": "0b9f5c1e-6c2a-4f0e-9d0b-2f1f3f0a7a11",
         *       "ownerId": "b1c2d3e4-5f60-4a7b-8c9d-0e1f2a3b4c5d",
         *       "title": "Write docs",
         *       "description": "Add a README",
         *       "createdAt": "2026-09-29T15:04:05.000Z",
         *       "done": false
         *     }
         */
        Task: {
            /** Format: uuid */
            id: string;
            /** @description The `sub` claim of the owner's JWT. Set on creation, never changes. */
            ownerId: string;
            title: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            done: boolean;
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            /** @description Opaque cursor for the next page, or `null` when there are no more pages. */
            nextToken: string | null;
        };
    };
    responses: {
        /** @description Missing, invalid or expired token (answered by API Gateway) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["Message"];
            };
        };
        /** @description The task does not exist or belongs to another user */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Task not found"
                 *     }
                 */
                "application/json": components["schemas"]["Message"];
            };
        };
        /** @description The body failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Event object failed validation",
                 *       "errors": [
                 *         "/body must have required property 'title'"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description `Content-Type` is not `application/json` */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Unsupported Media Type"
                 *     }
                 */
                "application/json": components["schemas"]["Message"];
            };
        };
        /** @description The body is not valid JSON */
        MalformedJson: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Invalid or malformed JSON was provided"
                 *     }
                 */
                "application/json": components["schemas"]["Message"];
            };
        };
        /** @description Unexpected failure */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Could not create task"
                 *     }
                 */
                "application/json": components["schemas"]["Message"];
            };
        };
    };
    parameters: {
        /** @description Task id (a UUID). */
        TaskId: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description When the operation was deprecated, as a structured-field date (RFC 9745): `@` followed by
         *     Unix seconds.
         */
        Deprecation: string;
        /**
         * @description The HTTP-date (RFC 8594) after which the operation may be removed. It is at least 90 days
         *     after the release that deprecated it.
         */
        Sunset: string;
        /**
         * @description The migration notes of the deprecation: a URL with `rel="deprecation"` (RFC 9745). The
         *     replacement is `PATCH` on the same path.
         */
        Link: string;
    };
    pathItems: never;
}
export type Message = components['schemas']['Message'];
export type ValidationError = components['schemas']['ValidationError'];
export type CreateTask = components['schemas']['CreateTask'];
export type UpdateTask = components['schemas']['UpdateTask'];
export type Task = components['schemas']['Task'];
export type TaskPage = components['schemas']['TaskPage'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseValidationError = components['responses']['ValidationError'];
export type ResponseUnsupportedMediaType = components['responses']['UnsupportedMediaType'];
export type ResponseMalformedJson = components['responses']['MalformedJson'];
export type ResponseServerError = components['responses']['ServerError'];
export type ParameterTaskId = components['parameters']['TaskId'];
export type HeaderDeprecation = components['headers']['Deprecation'];
export type HeaderSunset = components['headers']['Sunset'];
export type HeaderLink = components['headers']['Link'];
export type $defs = Record<string, never>;
export interface operations {
    hello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Greeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Hello, World!"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description Page size, an integer from 1 to 100. */
                limit?: number;
                /** @description The `nextToken` returned by the previous page. */
                nextToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            /** @description `limit` is not an integer from 1 to 100, or `nextToken` is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "limit must be an integer between 1 and 100"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Could not retrieve tasks */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Could not retrieve tasks"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Write docs",
                 *       "description": "Add a README"
                 *     }
                 */
                "application/json": components["schemas"]["CreateTask"];
            };
        };
        responses: {
            /** @description The created task */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["MalformedJson"];
            500: components["responses"]["ServerError"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id (a UUID). */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Could not retrieve task */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Could not retrieve task"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id (a UUID). */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "done": true
                 *     }
                 */
                "application/json": components["schemas"]["UpdateTask"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Task updated successfully"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description The body failed validation */
            400: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Event object failed validation",
                     *       "errors": [
                     *         "/body must have required property 'title'"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The task does not exist or belongs to another user */
            404: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Task not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description `Content-Type` is not `application/json` */
            415: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unsupported Media Type"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description The body is not valid JSON */
            422: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Invalid or malformed JSON was provided"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Could not update task */
            500: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["Link"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Could not update task"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id (a UUID). */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Task deleted successfully"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Could not delete task */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Could not delete task"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    patchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id (a UUID). */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "done": true
                 *     }
                 */
                "application/json": components["schemas"]["UpdateTask"];
            };
        };
        responses: {
            /** @description The updated task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["MalformedJson"];
            /** @description Could not update task */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Could not update task"
                     *     }
                     */
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
}
