Resources:
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tasks-${sls:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
